"scope: prepare-commit-msg-context":
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - "src/prepare-commit-msg-context/**"
              - "test/prepare-commit-msg-context/**"
"scope: semver-tool":
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - "src/semver-tool/**"
              - "test/semver-tool/**"
"scope: google-clasp":
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - "src/google-clasp/**"
              - "test/google-clasp/**"
"scope: google-gemini-cli":
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - "src/google-gemini-cli/**"
              - "test/google-gemini-cli/**"
