'scope: prepare-commit-msg-context':
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - 'src/prepare-commit-msg-context/**'
              - 'test/prepare-commit-msg-context/**'