#!/bin/sh

set -e

COMMIT_MSG_FILE="${1}"
COMMIT_SOURCE="${2}"
SHA1="${3}"

print_context() {
    echo "" >> "${COMMIT_MSG_FILE}"
    git diff --cached | sed 's/^/# /' >> "${COMMIT_MSG_FILE}"
}


case "${COMMIT_SOURCE},${SHA1}" in
    ",")
        print_context;;
    "template,")
        print_context;;
    *) ;;
esac
