name: "lint"
on:
  pull_request:
  push:
    branches:
      - "main"
    tags:
      - "!v*"

jobs:
  lint-features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - prepare-commit-msg-context
          - semver-tool
          - google-clasp
          - google-gemini-cli
    steps:
      - uses: actions/checkout@v4

      - name: Check feature script files
        run: |
          echo  "Linting ${FEATURE}..."
          scripts/lint-feature.sh "${FEATURE}"
          echo "Linting ${FEATURE} is done."
        shell: bash
        env:
          FEATURE: ${{ matrix.features }}

  lint-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
